# Generated by Django 2.1.7 on 2019-02-27 14:29

from django.db import migrations


def forwards_func(*args):
    pass


def reverse_func(*args):
    raise Exception('Cannot go backwards')


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
